"""Emit ReShade FX techniques from simulator pipelines (pixel shaders only).

Every pass becomes a pixel shader with its taps baked into a static const
array. The last pass is the composite: it resolves the final taps (typically
the fused upsample) and blends with the backbuffer using `Strength`.
Addressing is MIRROR, filtering LINEAR, matching the simulator.
"""
from __future__ import annotations

from .sim import Pipeline

HEADER = """// Auto-generated by topt (https://github.com/CeeJayDK/topt) - do not edit by hand.
#include "ReShade.fxh"

#ifndef TOPT_FORMAT
	#define TOPT_FORMAT RGB10A2 // intermediate format: RGB10A2, R11G11B10F or RGBA16F
#endif

uniform float TOPT_Strength <
	ui_type = "slider"; ui_min = 0.0; ui_max = 1.0;
	ui_label = "Blur strength (all TOPT techniques)";
> = 1.0;

sampler TOPT_sBackBuffer { Texture = ReShade::BackBufferTex; AddressU = MIRROR; AddressV = MIRROR; };
"""


def _size(div: int) -> str:
    return "BUFFER_WIDTH, BUFFER_HEIGHT" if div == 1 else f"BUFFER_WIDTH / {div}, BUFFER_HEIGHT / {div}"


def _f(v: float) -> str:
    s = f"{v:.9g}"
    return s if any(c in s for c in ".e") else s + ".0"


def _selector(p) -> str:
    """Per-pixel variant fraction t in [0, 1) from the integer pixel position `p`
    (float math only, so it also runs on D3D9)."""
    if p.tile == 1:
        return "0.0"
    if p.sel == "dot":  # (x + k*y) mod P, as a single dot/frac
        k = p.vmap[p.tile]  # the entry at (x=0, y=1) is k mod P
        return f"frac(dot(p, float2(1.0, {k}.0) / {p.tile}.0))"
    # 2x2 Bayer index / 4 == frac((2 * (x mod 2) + 3 * (y mod 2)) / 4); frac(p * 0.5) = (p mod 2) / 2
    if p.sel == "bayer" and p.tile == 2:
        return "frac(dot(frac(p * 0.5), float2(1.0, 1.5)))"
    if p.sel == "bayer" and p.tile == 4:  # 4x4 Bayer: 4 * bayer2(low bits) + bayer2(high bits), / 16
        return ("frac(dot(frac(p * 0.5), float2(1.0, 1.5))) + "
                "0.25 * frac(dot(frac(floor(p * 0.5) * 0.5), float2(1.0, 1.5)))")
    raise ValueError(f"no shader selector for {p.sel} tile {p.tile}")


def technique(pl: Pipeline, name: str, label: str = "", repeat: int = 1) -> str:
    """One technique (with its own textures) for pipeline `pl`."""
    assert all(p.warp is None for p in pl.passes), "warped taps are not supported"
    assert pl.passes[-1].div == 1, "the last pass must be full resolution (composite)"
    out = [f"// ---- {name}: {label or pl.method}"]
    last = len(pl.passes) - 1
    for i, p in enumerate(pl.passes[:-1]):
        out.append(f"texture {name}_t{i} {{ Width = BUFFER_WIDTH / {p.div}; Height = BUFFER_HEIGHT / {p.div}; "
                   f"Format = TOPT_FORMAT; }};" if p.div > 1 else
                   f"texture {name}_t{i} {{ Width = BUFFER_WIDTH; Height = BUFFER_HEIGHT; Format = TOPT_FORMAT; }};")
        out.append(f"sampler {name}_s{i} {{ Texture = {name}_t{i}; AddressU = MIRROR; AddressV = MIRROR; }};")
    for i, p in enumerate(pl.passes):
        j = pl.src_index(i)
        src = "TOPT_sBackBuffer" if j < 0 else f"{name}_s{j}"
        sdiv = pl.src_div(i)
        taps = ",\n\t".join(f"float3({_f(dx)}, {_f(dy)}, {_f(w)})" for dx, dy, w in p.taps)
        n = len(p.taps)
        out.append(f"static const float3 {name}_k{i}[{n}] = {{\n\t{taps}\n}};")
        ret = ("float3 o = tex2D(ReShade::BackBuffer, uv).rgb;\n"
               "\treturn float4(lerp(o, c, TOPT_Strength), 1.0);") if i == last else "return float4(c, 1.0);"
        if p.variants is None:
            out.append(f"""float4 {name}_PS{i}(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target
{{
	const float2 px = 1.0 / float2({_size(sdiv)});
	float3 c = 0.0;
	[unroll] for (int i = 0; i < {n}; i++)
		c += {name}_k{i}[i].z * tex2Dlod({src}, float4(uv + {name}_k{i}[i].xy * px, 0.0, 0.0)).rgb;
	{ret}
}}""")
        else:  # interleaved: rotate the base pattern per pixel by 2*pi*t, t = variant / n_variants
            out.append(f"""float4 {name}_PS{i}(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target
{{
	const float2 px = 1.0 / float2({_size(sdiv)});
	const float2 p = floor(pos.xy);
	const float t = {_selector(p)};
	float2 cs; sincos(6.2831853 * t, cs.y, cs.x);
	float3 c = 0.0;
	[unroll] for (int i = 0; i < {n}; i++)
	{{
		const float2 o = {name}_k{i}[i].xy;
		const float2 r = float2(o.x * cs.x - o.y * cs.y, o.x * cs.y + o.y * cs.x);
		c += {name}_k{i}[i].z * tex2Dlod({src}, float4(uv + r * px, 0.0, 0.0)).rgb;
	}}
	{ret}
}}""")
    passes = []
    for r in range(repeat):
        for i, p in enumerate(pl.passes):
            rt = "" if i == last else f" RenderTarget = {name}_t{i};"
            passes.append(f"\tpass p{r}_{i} {{ VertexShader = PostProcessVS; PixelShader = {name}_PS{i};{rt} }}")
    tip = (label or pl.method).replace('"', "'")
    out.append(f'technique {name} < ui_tooltip = "{tip}"; >\n{{\n' + "\n".join(passes) + "\n}")
    return "\n".join(out) + "\n"


def effect(items: list, repeat: int = 1) -> str:
    """items: [(pipeline, name, label)] -> full .fx source."""
    return HEADER + "\n" + "\n".join(technique(pl, n, lab, repeat) for pl, n, lab in items)
