/*------------------.
| :: TOPT Blur ::   |
'------------------*/
/*
  Fast Gaussian-like blur, generated by the topt texture-sample optimizer.

  One wide downsample pass (two for very large blurs), a Gaussian at low
  resolution whose width is computed at runtime (one 2D pass, or H + V), and a
  smooth "pinwheel" upsample fused into the final pass. Cost is nearly
  independent of the blur size above sigma ~8. Size 1 is a single pass: an
  exact Gaussian pinwheel of 2x2 texel blocks (sigma 0.7..1.3).

  Use it as is, or call TOPT_BlurResolve(uv) from your own final pass after
  running the TOPT_Down / TOPT_Blur (H/V) passes.
*/

#include "ReShade.fxh"

#ifndef TOPT_BLUR_SIZE
	#define TOPT_BLUR_SIZE 16 // blur sigma in pixels at 1080p (integer, 1..200; 1 = single pass, 0.7..1.3 with the fine-tune); scales with resolution
#endif
#ifndef TOPT_BLUR_FORMAT
	#define TOPT_BLUR_FORMAT RGB10A2 // intermediate format; R11G11B10F keeps HDR (> 1) values
#endif
#ifndef TOPT_BLUR_BLEND
	#define TOPT_BLUR_BLEND 0 // 1: blend with the screen by the output-merger blend state instead of in the shader
#endif

#define TOPT_SIGMA_SCREEN (TOPT_BLUR_SIZE * BUFFER_HEIGHT / 1080)

uniform float TOPT_SizeTune <
	ui_type = "slider"; ui_min = 0.7; ui_max = 1.33;
	ui_label = "Size fine-tune";
	ui_tooltip = "Multiplies the blur size set by TOPT_BLUR_SIZE.\nThe usable range of each size class is limited; the blur stops growing at its edges.";
> = 1.0;

uniform float TOPT_Strength <
	ui_type = "slider"; ui_min = 0.0; ui_max = 1.0;
	ui_label = "Strength";
> = 1.0;

uniform bool TOPT_ShowBlur <
	ui_label = "Show blur only";
> = false;

// ---- size class (chosen at compile time from the blur size and the resolution)
#if TOPT_SIGMA_SCREEN <= 1
	#define TOPT_CLASS 0 // '1'
	#define TOPT_SEP 0
#elif TOPT_SIGMA_SCREEN <= 2
	#define TOPT_CLASS 1 // '2'
	#define TOPT_SEP 0
#elif TOPT_SIGMA_SCREEN <= 3
	#define TOPT_CLASS 1 // '2' separable
	#define TOPT_SEP 1
#elif TOPT_SIGMA_SCREEN <= 6
	#define TOPT_CLASS 2 // '4s'
	#define TOPT_SEP 0
#elif TOPT_SIGMA_SCREEN <= 12
	#define TOPT_CLASS 3 // '4' separable
	#define TOPT_SEP 1
#elif TOPT_SIGMA_SCREEN <= 19
	#define TOPT_CLASS 4 // '8'
	#define TOPT_SEP 0
#elif TOPT_SIGMA_SCREEN <= 26
	#define TOPT_CLASS 4 // '8' separable
	#define TOPT_SEP 1
#elif TOPT_SIGMA_SCREEN <= 51
	#define TOPT_CLASS 5 // '16'
	#define TOPT_SEP 0
#elif TOPT_SIGMA_SCREEN <= 107
	#define TOPT_CLASS 6 // '32'
	#define TOPT_SEP 0
#elif TOPT_SIGMA_SCREEN <= 214
	#define TOPT_CLASS 7 // '64'
	#define TOPT_SEP 0
#else
	#define TOPT_CLASS 8 // '128'
	#define TOPT_SEP 0
#endif

#if TOPT_CLASS == 0 // '1': single pass, sigma 0.7..1.3 px
	#define TOPT_SMALL 1
	static const float2 TOPT_ARM[4] = { float2(1.0, -1.0), float2(2.0, 1.0), float2(3.0, -1.0), float2(3.0, -3.0) };
	#define TOPT_ARM_BLOCKS(sigma) (sigma <= 0.9 ? 2 : sigma <= 1.1 ? 3 : 4)
#elif TOPT_CLASS == 1 // '2': sigma 2.0..6.8 px
	#define TOPT_SMALL 0
	#define TOPT_STEPS 1
	#define TOPT_F1 2
	#define TOPT_F2 1
	#define TOPT_UPSTEPS 1
	static const float TOPT_C = 1.55127001;  // chain variance (px^2): sigma^2 = C + B * sl^2
	static const float TOPT_B = 3.83921331;
	static const float TOPT_SL_MIN = 0.8;
	static const float TOPT_SL_MAX = 3.4;
	#define TOPT_ND1 4
	static const float3 TOPT_DOWN1[4] = {
		float3(-0.75, -0.75, 0.25),
		float3(-0.75, 0.75, 0.25),
		float3(0.75, -0.75, 0.25),
		float3(0.75, 0.75, 0.25)
	};
	#define TOPT_NUP 4
	static const float3 TOPT_UP[4] = {
		float3(0.0803454039, 0.27318983, 0.25),
		float3(-0.27318983, 0.0803454039, 0.25),
		float3(-0.0803454039, -0.27318983, 0.25),
		float3(0.27318983, -0.0803454039, 0.25)
	};
#elif TOPT_CLASS == 2 // '4s': sigma 3.7..7.2 px
	#define TOPT_SMALL 0
	#define TOPT_STEPS 1
	#define TOPT_F1 4
	#define TOPT_F2 1
	#define TOPT_UPSTEPS 2
	static const float TOPT_C = 12.2066274;  // chain variance (px^2): sigma^2 = C + B * sl^2
	static const float TOPT_B = 15.3568532;
	static const float TOPT_SL_MIN = 0.3;
	static const float TOPT_SL_MAX = 1.6;
	#define TOPT_ND1 36
	static const float3 TOPT_DOWN1[36] = {
		float3(-4.6, -4.6, 9.53674316e-05),
		float3(-4.6, -2.78461538, 0.00123977661),
		float3(-4.6, -0.935483871, 0.00354766846),
		float3(-4.6, 0.935483871, 0.00354766846),
		float3(-4.6, 2.78461538, 0.00123977661),
		float3(-4.6, 4.6, 9.53674316e-05),
		float3(-2.78461538, -4.6, 0.00123977661),
		float3(-2.78461538, -2.78461538, 0.0161170959),
		float3(-2.78461538, -0.935483871, 0.0461196899),
		float3(-2.78461538, 0.935483871, 0.0461196899),
		float3(-2.78461538, 2.78461538, 0.0161170959),
		float3(-2.78461538, 4.6, 0.00123977661),
		float3(-0.935483871, -4.6, 0.00354766846),
		float3(-0.935483871, -2.78461538, 0.0461196899),
		float3(-0.935483871, -0.935483871, 0.131973267),
		float3(-0.935483871, 0.935483871, 0.131973267),
		float3(-0.935483871, 2.78461538, 0.0461196899),
		float3(-0.935483871, 4.6, 0.00354766846),
		float3(0.935483871, -4.6, 0.00354766846),
		float3(0.935483871, -2.78461538, 0.0461196899),
		float3(0.935483871, -0.935483871, 0.131973267),
		float3(0.935483871, 0.935483871, 0.131973267),
		float3(0.935483871, 2.78461538, 0.0461196899),
		float3(0.935483871, 4.6, 0.00354766846),
		float3(2.78461538, -4.6, 0.00123977661),
		float3(2.78461538, -2.78461538, 0.0161170959),
		float3(2.78461538, -0.935483871, 0.0461196899),
		float3(2.78461538, 0.935483871, 0.0461196899),
		float3(2.78461538, 2.78461538, 0.0161170959),
		float3(2.78461538, 4.6, 0.00123977661),
		float3(4.6, -4.6, 9.53674316e-05),
		float3(4.6, -2.78461538, 0.00123977661),
		float3(4.6, -0.935483871, 0.00354766846),
		float3(4.6, 0.935483871, 0.00354766846),
		float3(4.6, 2.78461538, 0.00123977661),
		float3(4.6, 4.6, 9.53674316e-05)
	};
	#define TOPT_NUP 4
	static const float3 TOPT_UP[4] = {
		float3(-0.5, -0.5, 0.25),
		float3(-0.5, 0.5, 0.25),
		float3(0.5, -0.5, 0.25),
		float3(0.5, 0.5, 0.25)
	};
#elif TOPT_CLASS == 3 // '4': sigma 6.7..13.6 px
	#define TOPT_SMALL 0
	#define TOPT_STEPS 1
	#define TOPT_F1 4
	#define TOPT_F2 1
	#define TOPT_UPSTEPS 1
	static const float TOPT_C = 6.12521583;  // chain variance (px^2): sigma^2 = C + B * sl^2
	static const float TOPT_B = 15.3568532;
	static const float TOPT_SL_MIN = 1.6;
	static const float TOPT_SL_MAX = 3.4;
	#define TOPT_ND1 16
	static const float3 TOPT_DOWN1[16] = {
		float3(-2.66666667, -2.66666667, 0.0087890625),
		float3(-2.66666667, -0.923076923, 0.0380859375),
		float3(-2.66666667, 0.923076923, 0.0380859375),
		float3(-2.66666667, 2.66666667, 0.0087890625),
		float3(-0.923076923, -2.66666667, 0.0380859375),
		float3(-0.923076923, -0.923076923, 0.165039062),
		float3(-0.923076923, 0.923076923, 0.165039062),
		float3(-0.923076923, 2.66666667, 0.0380859375),
		float3(0.923076923, -2.66666667, 0.0380859375),
		float3(0.923076923, -0.923076923, 0.165039062),
		float3(0.923076923, 0.923076923, 0.165039062),
		float3(0.923076923, 2.66666667, 0.0380859375),
		float3(2.66666667, -2.66666667, 0.0087890625),
		float3(2.66666667, -0.923076923, 0.0380859375),
		float3(2.66666667, 0.923076923, 0.0380859375),
		float3(2.66666667, 2.66666667, 0.0087890625)
	};
	#define TOPT_NUP 5
	static const float3 TOPT_UP[5] = {
		float3(0.328208186, 0.15456871, 0.186856012),
		float3(-0.15456871, 0.328208186, 0.186856012),
		float3(-0.328208186, -0.15456871, 0.186856012),
		float3(0.15456871, -0.328208186, 0.186856012),
		float3(0.0, 0.0, 0.252575952)
	};
#elif TOPT_CLASS == 4 // '8': sigma 13.4..27.1 px
	#define TOPT_SMALL 0
	#define TOPT_STEPS 1
	#define TOPT_F1 8
	#define TOPT_F2 1
	#define TOPT_UPSTEPS 1
	static const float TOPT_C = 22.8976017;  // chain variance (px^2): sigma^2 = C + B * sl^2
	static const float TOPT_B = 61.4274129;
	static const float TOPT_SL_MIN = 1.6;
	static const float TOPT_SL_MAX = 3.4;
	#define TOPT_ND1 25
	static const float3 TOPT_DOWN1[25] = {
		float3(-3.75, -3.75, 0.015625),
		float3(-3.75, -2.0, 0.03125),
		float3(-3.75, 0.0, 0.03125),
		float3(-3.75, 2.0, 0.03125),
		float3(-3.75, 3.75, 0.015625),
		float3(-2.0, -3.75, 0.03125),
		float3(-2.0, -2.0, 0.0625),
		float3(-2.0, 0.0, 0.0625),
		float3(-2.0, 2.0, 0.0625),
		float3(-2.0, 3.75, 0.03125),
		float3(0.0, -3.75, 0.03125),
		float3(0.0, -2.0, 0.0625),
		float3(0.0, 0.0, 0.0625),
		float3(0.0, 2.0, 0.0625),
		float3(0.0, 3.75, 0.03125),
		float3(2.0, -3.75, 0.03125),
		float3(2.0, -2.0, 0.0625),
		float3(2.0, 0.0, 0.0625),
		float3(2.0, 2.0, 0.0625),
		float3(2.0, 3.75, 0.03125),
		float3(3.75, -3.75, 0.015625),
		float3(3.75, -2.0, 0.03125),
		float3(3.75, 0.0, 0.03125),
		float3(3.75, 2.0, 0.03125),
		float3(3.75, 3.75, 0.015625)
	};
	#define TOPT_NUP 4
	static const float3 TOPT_UP[4] = {
		float3(0.0803454039, 0.27318983, 0.25),
		float3(-0.27318983, 0.0803454039, 0.25),
		float3(-0.0803454039, -0.27318983, 0.25),
		float3(0.27318983, -0.0803454039, 0.25)
	};
#elif TOPT_CLASS == 5 // '16': sigma 26.9..54.2 px
	#define TOPT_SMALL 0
	#define TOPT_STEPS 1
	#define TOPT_F1 16
	#define TOPT_F2 1
	#define TOPT_UPSTEPS 1
	static const float TOPT_C = 93.5548804;  // chain variance (px^2): sigma^2 = C + B * sl^2
	static const float TOPT_B = 245.709652;
	static const float TOPT_SL_MIN = 1.6;
	static const float TOPT_SL_MAX = 3.4;
	#define TOPT_ND1 81
	static const float3 TOPT_DOWN1[81] = {
		float3(-7.75, -7.75, 0.00390625),
		float3(-7.75, -6.0, 0.0078125),
		float3(-7.75, -4.0, 0.0078125),
		float3(-7.75, -2.0, 0.0078125),
		float3(-7.75, 0.0, 0.0078125),
		float3(-7.75, 2.0, 0.0078125),
		float3(-7.75, 4.0, 0.0078125),
		float3(-7.75, 6.0, 0.0078125),
		float3(-7.75, 7.75, 0.00390625),
		float3(-6.0, -7.75, 0.0078125),
		float3(-6.0, -6.0, 0.015625),
		float3(-6.0, -4.0, 0.015625),
		float3(-6.0, -2.0, 0.015625),
		float3(-6.0, 0.0, 0.015625),
		float3(-6.0, 2.0, 0.015625),
		float3(-6.0, 4.0, 0.015625),
		float3(-6.0, 6.0, 0.015625),
		float3(-6.0, 7.75, 0.0078125),
		float3(-4.0, -7.75, 0.0078125),
		float3(-4.0, -6.0, 0.015625),
		float3(-4.0, -4.0, 0.015625),
		float3(-4.0, -2.0, 0.015625),
		float3(-4.0, 0.0, 0.015625),
		float3(-4.0, 2.0, 0.015625),
		float3(-4.0, 4.0, 0.015625),
		float3(-4.0, 6.0, 0.015625),
		float3(-4.0, 7.75, 0.0078125),
		float3(-2.0, -7.75, 0.0078125),
		float3(-2.0, -6.0, 0.015625),
		float3(-2.0, -4.0, 0.015625),
		float3(-2.0, -2.0, 0.015625),
		float3(-2.0, 0.0, 0.015625),
		float3(-2.0, 2.0, 0.015625),
		float3(-2.0, 4.0, 0.015625),
		float3(-2.0, 6.0, 0.015625),
		float3(-2.0, 7.75, 0.0078125),
		float3(0.0, -7.75, 0.0078125),
		float3(0.0, -6.0, 0.015625),
		float3(0.0, -4.0, 0.015625),
		float3(0.0, -2.0, 0.015625),
		float3(0.0, 0.0, 0.015625),
		float3(0.0, 2.0, 0.015625),
		float3(0.0, 4.0, 0.015625),
		float3(0.0, 6.0, 0.015625),
		float3(0.0, 7.75, 0.0078125),
		float3(2.0, -7.75, 0.0078125),
		float3(2.0, -6.0, 0.015625),
		float3(2.0, -4.0, 0.015625),
		float3(2.0, -2.0, 0.015625),
		float3(2.0, 0.0, 0.015625),
		float3(2.0, 2.0, 0.015625),
		float3(2.0, 4.0, 0.015625),
		float3(2.0, 6.0, 0.015625),
		float3(2.0, 7.75, 0.0078125),
		float3(4.0, -7.75, 0.0078125),
		float3(4.0, -6.0, 0.015625),
		float3(4.0, -4.0, 0.015625),
		float3(4.0, -2.0, 0.015625),
		float3(4.0, 0.0, 0.015625),
		float3(4.0, 2.0, 0.015625),
		float3(4.0, 4.0, 0.015625),
		float3(4.0, 6.0, 0.015625),
		float3(4.0, 7.75, 0.0078125),
		float3(6.0, -7.75, 0.0078125),
		float3(6.0, -6.0, 0.015625),
		float3(6.0, -4.0, 0.015625),
		float3(6.0, -2.0, 0.015625),
		float3(6.0, 0.0, 0.015625),
		float3(6.0, 2.0, 0.015625),
		float3(6.0, 4.0, 0.015625),
		float3(6.0, 6.0, 0.015625),
		float3(6.0, 7.75, 0.0078125),
		float3(7.75, -7.75, 0.00390625),
		float3(7.75, -6.0, 0.0078125),
		float3(7.75, -4.0, 0.0078125),
		float3(7.75, -2.0, 0.0078125),
		float3(7.75, 0.0, 0.0078125),
		float3(7.75, 2.0, 0.0078125),
		float3(7.75, 4.0, 0.0078125),
		float3(7.75, 6.0, 0.0078125),
		float3(7.75, 7.75, 0.00390625)
	};
	#define TOPT_NUP 4
	static const float3 TOPT_UP[4] = {
		float3(0.0803454039, 0.27318983, 0.25),
		float3(-0.27318983, 0.0803454039, 0.25),
		float3(-0.0803454039, -0.27318983, 0.25),
		float3(0.27318983, -0.0803454039, 0.25)
	};
#elif TOPT_CLASS == 6 // '32': sigma 47.6..110.5 px
	#define TOPT_SMALL 0
	#define TOPT_STEPS 2
	#define TOPT_F1 16
	#define TOPT_F2 2
	#define TOPT_UPSTEPS 1
	static const float TOPT_C = 851.139854;  // chain variance (px^2): sigma^2 = C + B * sl^2
	static const float TOPT_B = 982.838606;
	static const float TOPT_SL_MIN = 1.2;
	static const float TOPT_SL_MAX = 3.4;
	#define TOPT_ND1 144
	static const float3 TOPT_DOWN1[144] = {
		float3(-10.6, -10.6, 5.96046448e-06),
		float3(-10.6, -8.78461538, 7.74860382e-05),
		float3(-10.6, -6.92670157, 0.000227689743),
		float3(-10.6, -4.99203187, 0.000299215317),
		float3(-10.6, -3.0, 0.000305175781),
		float3(-10.6, -1.0, 0.000305175781),
		float3(-10.6, 1.0, 0.000305175781),
		float3(-10.6, 3.0, 0.000305175781),
		float3(-10.6, 4.99203187, 0.000299215317),
		float3(-10.6, 6.92670157, 0.000227689743),
		float3(-10.6, 8.78461538, 7.74860382e-05),
		float3(-10.6, 10.6, 5.96046448e-06),
		float3(-8.78461538, -10.6, 7.74860382e-05),
		float3(-8.78461538, -8.78461538, 0.0010073185),
		float3(-8.78461538, -6.92670157, 0.00295996666),
		float3(-8.78461538, -4.99203187, 0.00388979912),
		float3(-8.78461538, -3.0, 0.00396728516),
		float3(-8.78461538, -1.0, 0.00396728516),
		float3(-8.78461538, 1.0, 0.00396728516),
		float3(-8.78461538, 3.0, 0.00396728516),
		float3(-8.78461538, 4.99203187, 0.00388979912),
		float3(-8.78461538, 6.92670157, 0.00295996666),
		float3(-8.78461538, 8.78461538, 0.0010073185),
		float3(-8.78461538, 10.6, 7.74860382e-05),
		float3(-6.92670157, -10.6, 0.000227689743),
		float3(-6.92670157, -8.78461538, 0.00295996666),
		float3(-6.92670157, -6.92670157, 0.00869774818),
		float3(-6.92670157, -4.99203187, 0.0114300251),
		float3(-6.92670157, -3.0, 0.0116577148),
		float3(-6.92670157, -1.0, 0.0116577148),
		float3(-6.92670157, 1.0, 0.0116577148),
		float3(-6.92670157, 3.0, 0.0116577148),
		float3(-6.92670157, 4.99203187, 0.0114300251),
		float3(-6.92670157, 6.92670157, 0.00869774818),
		float3(-6.92670157, 8.78461538, 0.00295996666),
		float3(-6.92670157, 10.6, 0.000227689743),
		float3(-4.99203187, -10.6, 0.000299215317),
		float3(-4.99203187, -8.78461538, 0.00388979912),
		float3(-4.99203187, -6.92670157, 0.0114300251),
		float3(-4.99203187, -4.99203187, 0.0150206089),
		float3(-4.99203187, -3.0, 0.0153198242),
		float3(-4.99203187, -1.0, 0.0153198242),
		float3(-4.99203187, 1.0, 0.0153198242),
		float3(-4.99203187, 3.0, 0.0153198242),
		float3(-4.99203187, 4.99203187, 0.0150206089),
		float3(-4.99203187, 6.92670157, 0.0114300251),
		float3(-4.99203187, 8.78461538, 0.00388979912),
		float3(-4.99203187, 10.6, 0.000299215317),
		float3(-3.0, -10.6, 0.000305175781),
		float3(-3.0, -8.78461538, 0.00396728516),
		float3(-3.0, -6.92670157, 0.0116577148),
		float3(-3.0, -4.99203187, 0.0153198242),
		float3(-3.0, -3.0, 0.015625),
		float3(-3.0, -1.0, 0.015625),
		float3(-3.0, 1.0, 0.015625),
		float3(-3.0, 3.0, 0.015625),
		float3(-3.0, 4.99203187, 0.0153198242),
		float3(-3.0, 6.92670157, 0.0116577148),
		float3(-3.0, 8.78461538, 0.00396728516),
		float3(-3.0, 10.6, 0.000305175781),
		float3(-1.0, -10.6, 0.000305175781),
		float3(-1.0, -8.78461538, 0.00396728516),
		float3(-1.0, -6.92670157, 0.0116577148),
		float3(-1.0, -4.99203187, 0.0153198242),
		float3(-1.0, -3.0, 0.015625),
		float3(-1.0, -1.0, 0.015625),
		float3(-1.0, 1.0, 0.015625),
		float3(-1.0, 3.0, 0.015625),
		float3(-1.0, 4.99203187, 0.0153198242),
		float3(-1.0, 6.92670157, 0.0116577148),
		float3(-1.0, 8.78461538, 0.00396728516),
		float3(-1.0, 10.6, 0.000305175781),
		float3(1.0, -10.6, 0.000305175781),
		float3(1.0, -8.78461538, 0.00396728516),
		float3(1.0, -6.92670157, 0.0116577148),
		float3(1.0, -4.99203187, 0.0153198242),
		float3(1.0, -3.0, 0.015625),
		float3(1.0, -1.0, 0.015625),
		float3(1.0, 1.0, 0.015625),
		float3(1.0, 3.0, 0.015625),
		float3(1.0, 4.99203187, 0.0153198242),
		float3(1.0, 6.92670157, 0.0116577148),
		float3(1.0, 8.78461538, 0.00396728516),
		float3(1.0, 10.6, 0.000305175781),
		float3(3.0, -10.6, 0.000305175781),
		float3(3.0, -8.78461538, 0.00396728516),
		float3(3.0, -6.92670157, 0.0116577148),
		float3(3.0, -4.99203187, 0.0153198242),
		float3(3.0, -3.0, 0.015625),
		float3(3.0, -1.0, 0.015625),
		float3(3.0, 1.0, 0.015625),
		float3(3.0, 3.0, 0.015625),
		float3(3.0, 4.99203187, 0.0153198242),
		float3(3.0, 6.92670157, 0.0116577148),
		float3(3.0, 8.78461538, 0.00396728516),
		float3(3.0, 10.6, 0.000305175781),
		float3(4.99203187, -10.6, 0.000299215317),
		float3(4.99203187, -8.78461538, 0.00388979912),
		float3(4.99203187, -6.92670157, 0.0114300251),
		float3(4.99203187, -4.99203187, 0.0150206089),
		float3(4.99203187, -3.0, 0.0153198242),
		float3(4.99203187, -1.0, 0.0153198242),
		float3(4.99203187, 1.0, 0.0153198242),
		float3(4.99203187, 3.0, 0.0153198242),
		float3(4.99203187, 4.99203187, 0.0150206089),
		float3(4.99203187, 6.92670157, 0.0114300251),
		float3(4.99203187, 8.78461538, 0.00388979912),
		float3(4.99203187, 10.6, 0.000299215317),
		float3(6.92670157, -10.6, 0.000227689743),
		float3(6.92670157, -8.78461538, 0.00295996666),
		float3(6.92670157, -6.92670157, 0.00869774818),
		float3(6.92670157, -4.99203187, 0.0114300251),
		float3(6.92670157, -3.0, 0.0116577148),
		float3(6.92670157, -1.0, 0.0116577148),
		float3(6.92670157, 1.0, 0.0116577148),
		float3(6.92670157, 3.0, 0.0116577148),
		float3(6.92670157, 4.99203187, 0.0114300251),
		float3(6.92670157, 6.92670157, 0.00869774818),
		float3(6.92670157, 8.78461538, 0.00295996666),
		float3(6.92670157, 10.6, 0.000227689743),
		float3(8.78461538, -10.6, 7.74860382e-05),
		float3(8.78461538, -8.78461538, 0.0010073185),
		float3(8.78461538, -6.92670157, 0.00295996666),
		float3(8.78461538, -4.99203187, 0.00388979912),
		float3(8.78461538, -3.0, 0.00396728516),
		float3(8.78461538, -1.0, 0.00396728516),
		float3(8.78461538, 1.0, 0.00396728516),
		float3(8.78461538, 3.0, 0.00396728516),
		float3(8.78461538, 4.99203187, 0.00388979912),
		float3(8.78461538, 6.92670157, 0.00295996666),
		float3(8.78461538, 8.78461538, 0.0010073185),
		float3(8.78461538, 10.6, 7.74860382e-05),
		float3(10.6, -10.6, 5.96046448e-06),
		float3(10.6, -8.78461538, 7.74860382e-05),
		float3(10.6, -6.92670157, 0.000227689743),
		float3(10.6, -4.99203187, 0.000299215317),
		float3(10.6, -3.0, 0.000305175781),
		float3(10.6, -1.0, 0.000305175781),
		float3(10.6, 1.0, 0.000305175781),
		float3(10.6, 3.0, 0.000305175781),
		float3(10.6, 4.99203187, 0.000299215317),
		float3(10.6, 6.92670157, 0.000227689743),
		float3(10.6, 8.78461538, 7.74860382e-05),
		float3(10.6, 10.6, 5.96046448e-06)
	};
	#define TOPT_ND2 25
	static const float3 TOPT_DOWN2[25] = {
		float3(-3.6, -3.6, 0.000381469727),
		float3(-3.6, -1.8, 0.00457763672),
		float3(-3.6, 0.0, 0.00961303711),
		float3(-3.6, 1.8, 0.00457763672),
		float3(-3.6, 3.6, 0.000381469727),
		float3(-1.8, -3.6, 0.00457763672),
		float3(-1.8, -1.8, 0.0549316406),
		float3(-1.8, 0.0, 0.115356445),
		float3(-1.8, 1.8, 0.0549316406),
		float3(-1.8, 3.6, 0.00457763672),
		float3(0.0, -3.6, 0.00961303711),
		float3(0.0, -1.8, 0.115356445),
		float3(0.0, 0.0, 0.242248535),
		float3(0.0, 1.8, 0.115356445),
		float3(0.0, 3.6, 0.00961303711),
		float3(1.8, -3.6, 0.00457763672),
		float3(1.8, -1.8, 0.0549316406),
		float3(1.8, 0.0, 0.115356445),
		float3(1.8, 1.8, 0.0549316406),
		float3(1.8, 3.6, 0.00457763672),
		float3(3.6, -3.6, 0.000381469727),
		float3(3.6, -1.8, 0.00457763672),
		float3(3.6, 0.0, 0.00961303711),
		float3(3.6, 1.8, 0.00457763672),
		float3(3.6, 3.6, 0.000381469727)
	};
	#define TOPT_NUP 4
	static const float3 TOPT_UP[4] = {
		float3(0.0803454039, 0.27318983, 0.25),
		float3(-0.27318983, 0.0803454039, 0.25),
		float3(-0.0803454039, -0.27318983, 0.25),
		float3(0.27318983, -0.0803454039, 0.25)
	};
#elif TOPT_CLASS == 7 // '64': sigma 107.7..216.7 px
	#define TOPT_SMALL 0
	#define TOPT_STEPS 2
	#define TOPT_F1 16
	#define TOPT_F2 4
	#define TOPT_UPSTEPS 1
	static const float TOPT_C = 1531.25434;  // chain variance (px^2): sigma^2 = C + B * sl^2
	static const float TOPT_B = 3931.35442;
	static const float TOPT_SL_MIN = 1.6;
	static const float TOPT_SL_MAX = 3.4;
	#define TOPT_ND1 81
	static const float3 TOPT_DOWN1[81] = {
		float3(-7.75, -7.75, 0.00390625),
		float3(-7.75, -6.0, 0.0078125),
		float3(-7.75, -4.0, 0.0078125),
		float3(-7.75, -2.0, 0.0078125),
		float3(-7.75, 0.0, 0.0078125),
		float3(-7.75, 2.0, 0.0078125),
		float3(-7.75, 4.0, 0.0078125),
		float3(-7.75, 6.0, 0.0078125),
		float3(-7.75, 7.75, 0.00390625),
		float3(-6.0, -7.75, 0.0078125),
		float3(-6.0, -6.0, 0.015625),
		float3(-6.0, -4.0, 0.015625),
		float3(-6.0, -2.0, 0.015625),
		float3(-6.0, 0.0, 0.015625),
		float3(-6.0, 2.0, 0.015625),
		float3(-6.0, 4.0, 0.015625),
		float3(-6.0, 6.0, 0.015625),
		float3(-6.0, 7.75, 0.0078125),
		float3(-4.0, -7.75, 0.0078125),
		float3(-4.0, -6.0, 0.015625),
		float3(-4.0, -4.0, 0.015625),
		float3(-4.0, -2.0, 0.015625),
		float3(-4.0, 0.0, 0.015625),
		float3(-4.0, 2.0, 0.015625),
		float3(-4.0, 4.0, 0.015625),
		float3(-4.0, 6.0, 0.015625),
		float3(-4.0, 7.75, 0.0078125),
		float3(-2.0, -7.75, 0.0078125),
		float3(-2.0, -6.0, 0.015625),
		float3(-2.0, -4.0, 0.015625),
		float3(-2.0, -2.0, 0.015625),
		float3(-2.0, 0.0, 0.015625),
		float3(-2.0, 2.0, 0.015625),
		float3(-2.0, 4.0, 0.015625),
		float3(-2.0, 6.0, 0.015625),
		float3(-2.0, 7.75, 0.0078125),
		float3(0.0, -7.75, 0.0078125),
		float3(0.0, -6.0, 0.015625),
		float3(0.0, -4.0, 0.015625),
		float3(0.0, -2.0, 0.015625),
		float3(0.0, 0.0, 0.015625),
		float3(0.0, 2.0, 0.015625),
		float3(0.0, 4.0, 0.015625),
		float3(0.0, 6.0, 0.015625),
		float3(0.0, 7.75, 0.0078125),
		float3(2.0, -7.75, 0.0078125),
		float3(2.0, -6.0, 0.015625),
		float3(2.0, -4.0, 0.015625),
		float3(2.0, -2.0, 0.015625),
		float3(2.0, 0.0, 0.015625),
		float3(2.0, 2.0, 0.015625),
		float3(2.0, 4.0, 0.015625),
		float3(2.0, 6.0, 0.015625),
		float3(2.0, 7.75, 0.0078125),
		float3(4.0, -7.75, 0.0078125),
		float3(4.0, -6.0, 0.015625),
		float3(4.0, -4.0, 0.015625),
		float3(4.0, -2.0, 0.015625),
		float3(4.0, 0.0, 0.015625),
		float3(4.0, 2.0, 0.015625),
		float3(4.0, 4.0, 0.015625),
		float3(4.0, 6.0, 0.015625),
		float3(4.0, 7.75, 0.0078125),
		float3(6.0, -7.75, 0.0078125),
		float3(6.0, -6.0, 0.015625),
		float3(6.0, -4.0, 0.015625),
		float3(6.0, -2.0, 0.015625),
		float3(6.0, 0.0, 0.015625),
		float3(6.0, 2.0, 0.015625),
		float3(6.0, 4.0, 0.015625),
		float3(6.0, 6.0, 0.015625),
		float3(6.0, 7.75, 0.0078125),
		float3(7.75, -7.75, 0.00390625),
		float3(7.75, -6.0, 0.0078125),
		float3(7.75, -4.0, 0.0078125),
		float3(7.75, -2.0, 0.0078125),
		float3(7.75, 0.0, 0.0078125),
		float3(7.75, 2.0, 0.0078125),
		float3(7.75, 4.0, 0.0078125),
		float3(7.75, 6.0, 0.0078125),
		float3(7.75, 7.75, 0.00390625)
	};
	#define TOPT_ND2 9
	static const float3 TOPT_DOWN2[9] = {
		float3(-1.75, -1.75, 0.0625),
		float3(-1.75, 0.0, 0.125),
		float3(-1.75, 1.75, 0.0625),
		float3(0.0, -1.75, 0.125),
		float3(0.0, 0.0, 0.25),
		float3(0.0, 1.75, 0.125),
		float3(1.75, -1.75, 0.0625),
		float3(1.75, 0.0, 0.125),
		float3(1.75, 1.75, 0.0625)
	};
	#define TOPT_NUP 4
	static const float3 TOPT_UP[4] = {
		float3(0.0803454039, 0.27318983, 0.25),
		float3(-0.27318983, 0.0803454039, 0.25),
		float3(-0.0803454039, -0.27318983, 0.25),
		float3(0.27318983, -0.0803454039, 0.25)
	};
#elif TOPT_CLASS == 8 // '128': sigma 215.4..433.5 px
	#define TOPT_SMALL 0
	#define TOPT_STEPS 2
	#define TOPT_F1 16
	#define TOPT_F2 8
	#define TOPT_UPSTEPS 1
	static const float TOPT_C = 6135.23566;  // chain variance (px^2): sigma^2 = C + B * sl^2
	static const float TOPT_B = 15725.4177;
	static const float TOPT_SL_MIN = 1.6;
	static const float TOPT_SL_MAX = 3.4;
	#define TOPT_ND1 81
	static const float3 TOPT_DOWN1[81] = {
		float3(-7.75, -7.75, 0.00390625),
		float3(-7.75, -6.0, 0.0078125),
		float3(-7.75, -4.0, 0.0078125),
		float3(-7.75, -2.0, 0.0078125),
		float3(-7.75, 0.0, 0.0078125),
		float3(-7.75, 2.0, 0.0078125),
		float3(-7.75, 4.0, 0.0078125),
		float3(-7.75, 6.0, 0.0078125),
		float3(-7.75, 7.75, 0.00390625),
		float3(-6.0, -7.75, 0.0078125),
		float3(-6.0, -6.0, 0.015625),
		float3(-6.0, -4.0, 0.015625),
		float3(-6.0, -2.0, 0.015625),
		float3(-6.0, 0.0, 0.015625),
		float3(-6.0, 2.0, 0.015625),
		float3(-6.0, 4.0, 0.015625),
		float3(-6.0, 6.0, 0.015625),
		float3(-6.0, 7.75, 0.0078125),
		float3(-4.0, -7.75, 0.0078125),
		float3(-4.0, -6.0, 0.015625),
		float3(-4.0, -4.0, 0.015625),
		float3(-4.0, -2.0, 0.015625),
		float3(-4.0, 0.0, 0.015625),
		float3(-4.0, 2.0, 0.015625),
		float3(-4.0, 4.0, 0.015625),
		float3(-4.0, 6.0, 0.015625),
		float3(-4.0, 7.75, 0.0078125),
		float3(-2.0, -7.75, 0.0078125),
		float3(-2.0, -6.0, 0.015625),
		float3(-2.0, -4.0, 0.015625),
		float3(-2.0, -2.0, 0.015625),
		float3(-2.0, 0.0, 0.015625),
		float3(-2.0, 2.0, 0.015625),
		float3(-2.0, 4.0, 0.015625),
		float3(-2.0, 6.0, 0.015625),
		float3(-2.0, 7.75, 0.0078125),
		float3(0.0, -7.75, 0.0078125),
		float3(0.0, -6.0, 0.015625),
		float3(0.0, -4.0, 0.015625),
		float3(0.0, -2.0, 0.015625),
		float3(0.0, 0.0, 0.015625),
		float3(0.0, 2.0, 0.015625),
		float3(0.0, 4.0, 0.015625),
		float3(0.0, 6.0, 0.015625),
		float3(0.0, 7.75, 0.0078125),
		float3(2.0, -7.75, 0.0078125),
		float3(2.0, -6.0, 0.015625),
		float3(2.0, -4.0, 0.015625),
		float3(2.0, -2.0, 0.015625),
		float3(2.0, 0.0, 0.015625),
		float3(2.0, 2.0, 0.015625),
		float3(2.0, 4.0, 0.015625),
		float3(2.0, 6.0, 0.015625),
		float3(2.0, 7.75, 0.0078125),
		float3(4.0, -7.75, 0.0078125),
		float3(4.0, -6.0, 0.015625),
		float3(4.0, -4.0, 0.015625),
		float3(4.0, -2.0, 0.015625),
		float3(4.0, 0.0, 0.015625),
		float3(4.0, 2.0, 0.015625),
		float3(4.0, 4.0, 0.015625),
		float3(4.0, 6.0, 0.015625),
		float3(4.0, 7.75, 0.0078125),
		float3(6.0, -7.75, 0.0078125),
		float3(6.0, -6.0, 0.015625),
		float3(6.0, -4.0, 0.015625),
		float3(6.0, -2.0, 0.015625),
		float3(6.0, 0.0, 0.015625),
		float3(6.0, 2.0, 0.015625),
		float3(6.0, 4.0, 0.015625),
		float3(6.0, 6.0, 0.015625),
		float3(6.0, 7.75, 0.0078125),
		float3(7.75, -7.75, 0.00390625),
		float3(7.75, -6.0, 0.0078125),
		float3(7.75, -4.0, 0.0078125),
		float3(7.75, -2.0, 0.0078125),
		float3(7.75, 0.0, 0.0078125),
		float3(7.75, 2.0, 0.0078125),
		float3(7.75, 4.0, 0.0078125),
		float3(7.75, 6.0, 0.0078125),
		float3(7.75, 7.75, 0.00390625)
	};
	#define TOPT_ND2 25
	static const float3 TOPT_DOWN2[25] = {
		float3(-3.75, -3.75, 0.015625),
		float3(-3.75, -2.0, 0.03125),
		float3(-3.75, 0.0, 0.03125),
		float3(-3.75, 2.0, 0.03125),
		float3(-3.75, 3.75, 0.015625),
		float3(-2.0, -3.75, 0.03125),
		float3(-2.0, -2.0, 0.0625),
		float3(-2.0, 0.0, 0.0625),
		float3(-2.0, 2.0, 0.0625),
		float3(-2.0, 3.75, 0.03125),
		float3(0.0, -3.75, 0.03125),
		float3(0.0, -2.0, 0.0625),
		float3(0.0, 0.0, 0.0625),
		float3(0.0, 2.0, 0.0625),
		float3(0.0, 3.75, 0.03125),
		float3(2.0, -3.75, 0.03125),
		float3(2.0, -2.0, 0.0625),
		float3(2.0, 0.0, 0.0625),
		float3(2.0, 2.0, 0.0625),
		float3(2.0, 3.75, 0.03125),
		float3(3.75, -3.75, 0.015625),
		float3(3.75, -2.0, 0.03125),
		float3(3.75, 0.0, 0.03125),
		float3(3.75, 2.0, 0.03125),
		float3(3.75, 3.75, 0.015625)
	};
	#define TOPT_NUP 4
	static const float3 TOPT_UP[4] = {
		float3(0.0803454039, 0.27318983, 0.25),
		float3(-0.27318983, 0.0803454039, 0.25),
		float3(-0.0803454039, -0.27318983, 0.25),
		float3(0.27318983, -0.0803454039, 0.25)
	};
#endif

sampler TOPT_sBackBuffer { Texture = ReShade::BackBufferTex; AddressU = MIRROR; AddressV = MIRROR; };

#if TOPT_SMALL
// Single pass: centre texel + 4-fold pinwheel of 2x2 texel blocks, each block's
// Gaussian weights reproduced exactly by one bilinear fetch.
float3 TOPT_BlurResolve(float2 uv)
{
	const float sigma = clamp(TOPT_BLUR_SIZE * TOPT_SizeTune * BUFFER_HEIGHT / 1080.0, 0.7, 1.3);
	const float k = -0.5 / (sigma * sigma);
	const int n = TOPT_ARM_BLOCKS(sigma); // blocks per arm: the same for every pixel
	float3 c = tex2Dlod(TOPT_sBackBuffer, float4(uv, 0.0, 0.0)).rgb;
	float wsum = 1.0;
	[unroll] for (int i = 0; i < 4; i++)
	{
		[branch] if (i < n)
		{
			const float2 b = TOPT_ARM[i];
			const float4 g = exp(k * float4(b.x, b.x + 1.0, b.y, b.y + 1.0) * float4(b.x, b.x + 1.0, b.y, b.y + 1.0));
			const float2 o = float2(b.x + g.y / (g.x + g.y), b.y + g.w / (g.z + g.w)); // pixels
			const float w = (g.x + g.y) * (g.z + g.w);
			c += w * (tex2Dlod(TOPT_sBackBuffer, float4(uv + o * BUFFER_PIXEL_SIZE, 0.0, 0.0)).rgb
			        + tex2Dlod(TOPT_sBackBuffer, float4(uv + float2(-o.y, o.x) * BUFFER_PIXEL_SIZE, 0.0, 0.0)).rgb
			        + tex2Dlod(TOPT_sBackBuffer, float4(uv - o * BUFFER_PIXEL_SIZE, 0.0, 0.0)).rgb
			        + tex2Dlod(TOPT_sBackBuffer, float4(uv + float2(o.y, -o.x) * BUFFER_PIXEL_SIZE, 0.0, 0.0)).rgb);
			wsum += 4.0 * w;
		}
	}
	return c / wsum;
}
#else
#define TOPT_RMAX 9   // low-res kernel radius limit (texels)
#define TOPT_NP ((TOPT_RMAX + 1) / 2) // max merged pairs per side

#define TOPT_DIV1 TOPT_F1
#define TOPT_DIV2 (TOPT_F1 * TOPT_F2)

texture TOPT_tDown1 { Width = BUFFER_WIDTH / TOPT_DIV1; Height = BUFFER_HEIGHT / TOPT_DIV1; Format = TOPT_BLUR_FORMAT; };
sampler TOPT_sDown1 { Texture = TOPT_tDown1; AddressU = MIRROR; AddressV = MIRROR; };
#if TOPT_STEPS > 1
texture TOPT_tDown2 { Width = BUFFER_WIDTH / TOPT_DIV2; Height = BUFFER_HEIGHT / TOPT_DIV2; Format = TOPT_BLUR_FORMAT; };
sampler TOPT_sDown2 { Texture = TOPT_tDown2; AddressU = MIRROR; AddressV = MIRROR; };
	#define TOPT_sLow TOPT_sDown2
	#define TOPT_DIVL TOPT_DIV2
#else
	#define TOPT_sLow TOPT_sDown1
	#define TOPT_DIVL TOPT_DIV1
#endif
#if TOPT_SEP
texture TOPT_tBlurH { Width = BUFFER_WIDTH / TOPT_DIVL; Height = BUFFER_HEIGHT / TOPT_DIVL; Format = TOPT_BLUR_FORMAT; };
sampler TOPT_sBlurH { Texture = TOPT_tBlurH; AddressU = MIRROR; AddressV = MIRROR; };
#endif
texture TOPT_tBlur { Width = BUFFER_WIDTH / TOPT_DIVL; Height = BUFFER_HEIGHT / TOPT_DIVL; Format = TOPT_BLUR_FORMAT; };
sampler TOPT_sBlur { Texture = TOPT_tBlur; AddressU = MIRROR; AddressV = MIRROR; };
#if TOPT_UPSTEPS > 1 // intermediate x2 upsample to 1/(DIVL/2) resolution
	#define TOPT_DIVU (TOPT_DIVL / 2)
texture TOPT_tUp { Width = BUFFER_WIDTH / TOPT_DIVU; Height = BUFFER_HEIGHT / TOPT_DIVU; Format = TOPT_BLUR_FORMAT; };
sampler TOPT_sUp { Texture = TOPT_tUp; AddressU = MIRROR; AddressV = MIRROR; };
	#define TOPT_sFinal TOPT_sUp
	#define TOPT_DIVF TOPT_DIVU
#else
	#define TOPT_sFinal TOPT_sBlur
	#define TOPT_DIVF TOPT_DIVL
#endif

float4 TOPT_Down1PS(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target
{
	const float2 px = BUFFER_PIXEL_SIZE;
	float3 c = 0.0;
	[unroll] for (int i = 0; i < TOPT_ND1; i++)
		c += TOPT_DOWN1[i].z * tex2Dlod(TOPT_sBackBuffer, float4(uv + TOPT_DOWN1[i].xy * px, 0.0, 0.0)).rgb;
	return float4(c, 1.0);
}

#if TOPT_STEPS > 1
float4 TOPT_Down2PS(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target
{
	const float2 px = 1.0 / float2(BUFFER_WIDTH / TOPT_DIV1, BUFFER_HEIGHT / TOPT_DIV1);
	float3 c = 0.0;
	[unroll] for (int i = 0; i < TOPT_ND2; i++)
		c += TOPT_DOWN2[i].z * tex2Dlod(TOPT_sDown1, float4(uv + TOPT_DOWN2[i].xy * px, 0.0, 0.0)).rgb;
	return float4(c, 1.0);
}
#endif

// Low-res Gaussian: width from the requested blur size, pairs of texels merged
// into one bilinear fetch; one 2D pass (outer product) or H then V passes.
float TOPT_LowSigma()
{
	const float sigma = TOPT_BLUR_SIZE * TOPT_SizeTune * BUFFER_HEIGHT / 1080.0;
	return clamp(sqrt(max(sigma * sigma - TOPT_C, 0.0) / TOPT_B), TOPT_SL_MIN, TOPT_SL_MAX);
}

// Pair m >= 1 of the 1D kernel (texels 2m-1 and 2m, the second only if within r)
// as (offset, weight); k = -1 / (2 sl^2).
float2 TOPT_Pair(int m, float k, int r)
{
	const float j = 2 * m - 1;
	const float a = exp(k * j * j);
	const float b = j + 1.0 <= r ? exp(k * (j + 1.0) * (j + 1.0)) : 0.0;
	return float2(j + b / (a + b), a + b);
}

float4 TOPT_BlurPS(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target
{
	const float2 px = 1.0 / float2(BUFFER_WIDTH / TOPT_DIVL, BUFFER_HEIGHT / TOPT_DIVL);
	const float sl = TOPT_LowSigma();
	const int r = min(TOPT_RMAX, (int)ceil(2.5 * sl));
	const int np = (r + 1) / 2; // pairs used; the same for every pixel, so the branches never diverge
	const float k = -0.5 / (sl * sl);

	float2 t[TOPT_NP + 1];
	t[0] = float2(0.0, 1.0);
	float wsum = 1.0;
	[unroll] for (int m = 1; m <= TOPT_NP; m++)
	{
		t[m] = TOPT_Pair(m, k, r);
		wsum += m <= np ? 2.0 * t[m].y : 0.0;
	}

	float3 c = 0.0;
	[unroll] for (int y = -TOPT_NP; y <= TOPT_NP; y++)
	{
		[branch] if (abs(y) <= np)
		{
			const float2 ty = t[abs(y)];
			[unroll] for (int x = -TOPT_NP; x <= TOPT_NP; x++)
			{
				[branch] if (abs(x) <= np)
				{
					const float2 tx = t[abs(x)];
					const float2 o = float2(x < 0 ? -tx.x : tx.x, y < 0 ? -ty.x : ty.x);
					c += tx.y * ty.y * tex2Dlod(TOPT_sLow, float4(uv + o * px, 0.0, 0.0)).rgb;
				}
			}
		}
	}
	return float4(c / (wsum * wsum), 1.0);
}

#if TOPT_SEP
float3 TOPT_Blur1D(sampler s, float2 uv, float2 dir)
{
	const float2 d = dir / float2(BUFFER_WIDTH / TOPT_DIVL, BUFFER_HEIGHT / TOPT_DIVL);
	const float sl = TOPT_LowSigma();
	const int r = min(TOPT_RMAX, (int)ceil(2.5 * sl));
	const int np = (r + 1) / 2;
	const float k = -0.5 / (sl * sl);

	float3 c = tex2Dlod(s, float4(uv, 0.0, 0.0)).rgb;
	float wsum = 1.0;
	[unroll] for (int m = 1; m <= TOPT_NP; m++)
	{
		[branch] if (m <= np)
		{
			const float2 p = TOPT_Pair(m, k, r);
			c += p.y * (tex2Dlod(s, float4(uv + p.x * d, 0.0, 0.0)).rgb + tex2Dlod(s, float4(uv - p.x * d, 0.0, 0.0)).rgb);
			wsum += 2.0 * p.y;
		}
	}
	return c / wsum;
}

float4 TOPT_BlurHPS(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target
{
	return float4(TOPT_Blur1D(TOPT_sLow, uv, float2(1.0, 0.0)), 1.0);
}

float4 TOPT_BlurVPS(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target
{
	return float4(TOPT_Blur1D(TOPT_sBlurH, uv, float2(0.0, 1.0)), 1.0);
}
#endif

#if TOPT_UPSTEPS > 1
float4 TOPT_UpPS(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target
{
	const float2 px = 1.0 / float2(BUFFER_WIDTH / TOPT_DIVL, BUFFER_HEIGHT / TOPT_DIVL);
	float3 c = 0.0;
	[unroll] for (int i = 0; i < TOPT_NUP; i++)
		c += TOPT_UP[i].z * tex2Dlod(TOPT_sBlur, float4(uv + TOPT_UP[i].xy * px, 0.0, 0.0)).rgb;
	return float4(c, 1.0);
}
#endif

// The blurred image at uv (full resolution): smooth upsample of the low-res
// blur. Call this from your own composite pass.
float3 TOPT_BlurResolve(float2 uv)
{
	const float2 px = 1.0 / float2(BUFFER_WIDTH / TOPT_DIVF, BUFFER_HEIGHT / TOPT_DIVF);
	float3 c = 0.0;
	[unroll] for (int i = 0; i < TOPT_NUP; i++)
		c += TOPT_UP[i].z * tex2Dlod(TOPT_sFinal, float4(uv + TOPT_UP[i].xy * px, 0.0, 0.0)).rgb;
	return c;
}
#endif // TOPT_SMALL

#if TOPT_BLUR_BLEND
// The pass blends: screen = blur * a + screen * (1 - a). The shader neither reads
// the screen nor lerps. Blending uses the stored (non-sRGB) values, as the
// shader lerp below does, so the result is the same.
float4 TOPT_CompositePS(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target
{
	return float4(TOPT_BlurResolve(uv), TOPT_ShowBlur ? 1.0 : TOPT_Strength);
}
#else
float4 TOPT_CompositePS(float4 pos : SV_Position, float2 uv : TEXCOORD) : SV_Target
{
	const float3 blur = TOPT_BlurResolve(uv);
	if (TOPT_ShowBlur)
		return float4(blur, 1.0);
	const float3 o = tex2D(ReShade::BackBuffer, uv).rgb;
	return float4(lerp(o, blur, TOPT_Strength), 1.0);
}
#endif

technique TOPT_Blur < ui_tooltip = "Fast Gaussian-like blur (topt).\nSet the size with the TOPT_BLUR_SIZE preprocessor definition (sigma in pixels at 1080p)."; >
{
#if !TOPT_SMALL
	pass Down1 { VertexShader = PostProcessVS; PixelShader = TOPT_Down1PS; RenderTarget = TOPT_tDown1; }
#if TOPT_STEPS > 1
	pass Down2 { VertexShader = PostProcessVS; PixelShader = TOPT_Down2PS; RenderTarget = TOPT_tDown2; }
#endif
#if TOPT_SEP
	pass BlurH { VertexShader = PostProcessVS; PixelShader = TOPT_BlurHPS; RenderTarget = TOPT_tBlurH; }
	pass BlurV { VertexShader = PostProcessVS; PixelShader = TOPT_BlurVPS; RenderTarget = TOPT_tBlur; }
#else
	pass Blur { VertexShader = PostProcessVS; PixelShader = TOPT_BlurPS; RenderTarget = TOPT_tBlur; }
#endif
#if TOPT_UPSTEPS > 1
	pass Up { VertexShader = PostProcessVS; PixelShader = TOPT_UpPS; RenderTarget = TOPT_tUp; }
#endif
#endif
	pass Composite
	{
		VertexShader = PostProcessVS; PixelShader = TOPT_CompositePS;
#if TOPT_BLUR_BLEND
		BlendEnable = true; BlendOp = ADD; SrcBlend = SRCALPHA; DestBlend = INVSRCALPHA;
		RenderTargetWriteMask = 7; // keep the screen's alpha
#endif
	}
}
